"""
CENTRA-NF Universal SDK - Python Package

A deterministic protocol-bound language system with military-grade security.

## Quick Start

```python
import centra_nf

# Compile a CENTRA-NF program
program = centra_nf.compile('''
IDENTIFICATION DIVISION.
ENVIRONMENT DIVISION.
DATA DIVISION.
PROCEDURE DIVISION.
''')

# Create and execute on runtime
runtime = centra_nf.Runtime()
runtime.execute(program)

# Cryptographic operations
digest = centra_nf.sha256(b"data")
encrypted = centra_nf.encrypt(b"secret")
decrypted = centra_nf.decrypt(encrypted)

# Version info
print(centra_nf.version())
print(centra_nf.build_info())
```

## Architecture

CENTRA-NF employs **Layer-Discipline** strict separation:

- **Layer 1: Compiler** - Source → AST → IR (deterministic frontend)
- **Layer 2: Runtime** - Execute IR against buffers (deterministic execution)
- **Layer 3: Security** - Cryptographic operations (constant-time)
- **Layer 4: Quantum** - Post-quantum cryptography (ML-KEM, ML-DSA, SLH-DSA)
- **L5-L8: Infrastructure** - Protocol, network, storage, verification

## Key Guarantees

1. **Determinism**: Same input → identical output (bytewise across platforms)
2. **Zero Panics**: All error paths are `Result<T, E>`
3. **Constant-Time Crypto**: Resistant to timing side-channels
4. **No Global Mutable State**: Thread-safe by construction

## Installation

### From PyPI (Recommended)
```bash
pip install centra-nf
```

### Development Build
```bash
git clone https://github.com/centranf1/v.git
cd v
pip install maturin
maturin develop --release
```

### Build Production Wheel
```bash
maturin build --release
# Wheels generated in:
# dist/centra_nf-1.0.0-cp310-...-linux_x86_64.whl
# dist/centra_nf-1.0.0-cp311-...-linux_x86_64.whl
# dist/centra_nf-1.0.0-cp312-...-linux_x86_64.whl
# dist/centra_nf-1.0.0-cp313-...-linux_x86_64.whl
```

## API Reference

### Compilation

```python
program = centra_nf.compile(source: str) -> Program
```

Compile CENTRA-NF source code to intermediate representation.

**Arguments:**
- `source` (str): CENTRA-NF source code with 4 divisions

**Returns:**
- `Program`: Compiled program (opaque handle)

**Raises:**
- `RuntimeError`: Compilation failed

**Example:**
```python
>>> prog = centra_nf.compile("IDENTIFICATION DIVISION...")
>>> type(prog)
<class 'centra_nf.Program'>
```

### Runtime Execution

```python
runtime = centra_nf.Runtime()
runtime.execute(program: Program) -> None
```

Execute compiled program on runtime engine.

**Example:**
```python
>>> runtime = centra_nf.Runtime()
>>> runtime.execute(program)
```

### Cryptography

#### SHA-256 (Deterministic Hashing)

```python
digest = centra_nf.sha256(data: bytes) -> str
```

Compute SHA-256 hash in constant time.

**Returns:** Lowercase hex string (64 characters)

**Example:**
```python
>>> centra_nf.sha256(b"Hello")
'185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969'
```

#### AES-256-GCM (Authenticated Encryption)

```python
ciphertext = centra_nf.encrypt(plaintext: bytes) -> bytes
plaintext = centra_nf.decrypt(ciphertext: bytes) -> bytes
```

Encrypt/decrypt with AES-256-GCM (random nonce per encryption).

**Example:**
```python
>>> secret = b"Confidential message"
>>> encrypted = centra_nf.encrypt(secret)
>>> decrypted = centra_nf.decrypt(encrypted)
>>> decrypted == secret
True
```

### Utilities

```python
version() -> str
build_info() -> str
```

**Example:**
```python
>>> centra_nf.version()
'CENTRA-NF 1.0.0'
>>> centra_nf.build_info()
'CENTRA-NF 1.0.0\\nBuilt: ...\\nProfile: release (Military-Grade optimized)'
```

## Multi-Language Support

### C/C++ (via ctypes or direct linking)

```c
#include "centra_nf.h"

// Compile
CnfProgramHandle *program = NULL;
CnfError err = cnf_compile("IDENTIFICATION DIVISION...", &program);
if (err.code != 0) return error;

// Hash
char hash[65];
err = cnf_sha256(data, data_len, hash, 65);

// Cleanup
cnf_free_program(program);
```

### C Bindings (auto-generated by cbindgen)

```bash
cbindgen -o centra_nf.h
# Generates: centra_nf.h (C-compatible headers)
```

## Performance Metrics

Built with Military-Grade optimization profiles:

| Profile | Compile Time | Binary Size | Optimization |
|---------|--------------|-------------|-------------|
| debug | 15s | 850 MB | None (-O0) |
| release | 45s | 12 MB | Balanced (-O3 thin-LTO) |
| release-lto | 8min | 10 MB | Maximum (-O3 fat-LTO) |
| release-thin-lto | 2min | 11 MB | Fast (-O3 thin-LTO) |

## Thread Safety

CENTRA-NF is thread-safe by design:

```python
import threading

runtime1 = centra_nf.Runtime()
runtime2 = centra_nf.Runtime()

def worker(runtime):
    program = centra_nf.compile("IDENTIFICATION DIVISION...")
    runtime.execute(program)

# Safe concurrent execution
t1 = threading.Thread(target=worker, args=(runtime1,))
t2 = threading.Thread(target=worker, args=(runtime2,))
t1.start()
t2.start()
t1.join()
t2.join()
```

## Error Handling

All functions return `Result` (Rust semantics) converted to Python exceptions:

```python
try:
    program = centra_nf.compile("INVALID DIVISION_ORDER")
except RuntimeError as e:
    print(f"Compilation failed: {e}")
```

Error codes (0-10) mapped to descriptive messages.

## Security Considerations

1. **Key Material**: Automatically zeroed using `zeroize` crate
2. **Deterministic**: Same input → identical output (no randomness)
3. **Constant-Time**: Cryptographic functions resist timing attacks
4. **Memory Safety**: Rust enforces bounds checking, no buffer overflows
5. **No Panics**: Production code never panics

## License

Proprietary. See LICENSE for details.

## Community

- **Repository**: https://github.com/centranf1/v
- **Issues**: https://github.com/centranf1/v/issues
- **Discussions**: https://github.com/centranf1/v/discussions

---

**CENTRA-NF v1.0.0** - Built for deterministic, mission-critical data center operations.
"""

__version__ = "1.0.0"
__author__ = "CENTRA-NF Dev Team"
__license__ = "Proprietary"

# Import compiled extension module
try:
    from centra_nf.core import (
        # Version and build info
        version,
        build_info,
        
        # Cryptography
        sha256,
        encrypt,
        decrypt,
    )
except ImportError as e:
    raise ImportError(
        "Failed to import CENTRA-NF compiled extension module.\n"
        "Ensure maturin is installed and the module was built:\n"
        "  pip install maturin\n"
        "  maturin develop --release"
    ) from e

# Public API
__all__ = [
    "version",
    "build_info",
    "sha256",
    "encrypt",
    "decrypt",
]

# Convenience functions
def get_version() -> str:
    """Get CENTRA-NF version string."""
    return version()


def get_build_info() -> str:
    """Get detailed build information."""
    return build_info()
